#cloud-config
repo_update: true
repo_upgrade: all
package_upgrade: true

bootcmd:
 - [ cloud-init-per, once, mkfs, -t, ext4, /dev/sdb ]

fs_setup:
 - cmd: mkfs -t %(filesystem)s -L %(label)s %(device)s
   label: data
   filesystem: 'ext4'
   overwrite: false
   device: '/dev/sdb'

mounts:
 - [ /dev/sdb, /data, "ext4", "defaults,nofail", "0", "2" ]

write_files:
- path: /etc/docker/daemon.json
  content: |
    {
      "data-root": "/data",
      "bip": "${gw}/24",
      "default-address-pools":
      [
        {"base":"${vpc_cidr}","size":24}
      ],
      "dns": ["${gw}", "${dns}"]
    }
  owner: "root:root"
  permissions: "0777"
- path: /etc/systemd/resolved.conf.d/consul.conf
  content: |
    [Resolve]
    DNS=${gw}:8600
    DNSSEC=false
    Domains=~${consul_domain}
  owner: "root:root"
  permissions: "0777"
- path: /etc/systemd/resolved.conf.d/docker.conf
  content: |
    [Resolve]
    DNSStubListener=yes
    DNSStubListenerExtra=${gw}
  owner: "root:root"
  permissions: "0777"
runcmd:
  - [service, systemd-resolved, restart]